basic:
    name: 'Client Center Websites'
    environments:
        production: 'https://sage.clientcenter360.com/'
        staging: 'https://test-clientcenter360-sage.pantheonsite.io/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 320
        - 640
        - 768
        - 1024
        - 1200
        - 1440
    pages:
        - /
        - /browse-by-theme
        - /contact
        - /whats-trending
        - /search
        - /portal
        - '/portal/?ppage=list&module=Themes&origin=CRM'
        - /project-profile
        - /lets-connect
        - /register-form-2
        - /browse-by-market
        - /best-sellers
        - /register-form
        - /website-feedback
        - /support
        - /sub_category_post/back-to-work-all-products
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 5
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
